FROM docker.io/library/node:24.18.1@sha256:19cd848a0e073d34bd8cd5545a1b6b4d28489b3e3b607366621ced442bd5f6b4

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

